#!/bin/bash
awk '{	
	was=0
	if (index($0,"2") != 0 && was == 0) {
		print $1 " bad"
		was=1
	}
	if (index($0,"3") != 0 && was == 0) {
		print $1 " good"
		was=1
	}
	if (index($0,"4") != 0 && was == 0) {
		print $1 " great"
		was=1
	}
	if (index($0,"5") != 0 && was == 0) {
		print $1 " perfect"
		was=1
	}
}' file.txt >> tmp
cat tmp > file.txt
rm tmp
