#!/bin/bash

while true
do
	echo "1. Nano"
	echo "2. Vi"
	echo "3. Links"
	echo "4. Exit"
	
	read choice
	case $choice in
		1)
			nano
		;;
		2)
			vi
		;;
		3)
			links
		;;
		4)
			break
		;;
		*)
			echo "Wrong choice"
		;;
	esac
done
